### PR TITLE
Federal UI

### PR DESCRIPTION
**Pull request by KipCrossing**
In reference to #34

Introduces classes:
- BillMeta
- Bill

and functions:
- `get_bills_metadata()`
- `get_bill()`

This is to start a dicsussion about the Aligned UI

### CODE REVIEW

**Comment by KipCrossing** [comment]
@connorhsm @king-millez 

The main thing is that we need to figure out what data is general acros all parliments `[title, id, link]` and what is not eg `text_doc_link`. We can also dicsuss the inheritance method I used to pass the datatypes.

**Comment by king-millez** [comment]
Oh dear I have to do things

**Comment by KipCrossing** [comment]
I'm going to collect all the info types into one place to make it easier to compare.

### Federal 

```python
CHAMBER = "chamber"
SHORT_TITLE = "short_title"
INTRO_HOUSE = "intro_house"
PASSED_HOUSE = "passed_house"
INTRO_SENATE = "intro_senate"
PASSED_SENATE = "passed_senate"
ASSENT_DATE = "assent_date"
URL = "url"
ACT_NO = "act_no"
DOC = "doc"
PDF = "pdf"
HTML = "html"
SUMMARY = "summary"
SPONSOR = "sponsor"
PORTFOLIO = "portfolio"
TEXT_LINK = "text_link"
EM_LINK = "em_link"
ID = "id"
CURRENT_READING = "current_reading"
READINGS = "readings"
```

### NSW

```python
URL = 'url'
TITLE = 'title'
STATUS = 'status'
ORIGIN = 'origin'
ACT_NO = 'act_no'
YEAR = 'year'
TYPE = 'type'
CARRIAGE_MEMBER = 'carriage_member'
LONG_TITLE = 'long_title'
BILL_TEXT = 'text'
```

### ACT

```python
DATE = 'date'
URL = 'url'
TITLE = 'title'
DESCRIPTION = 'description'
PRESENTED_BY = 'presented_by'
TYPE = 'type'
STATUS = 'status'
TEXT_URL = 'text_url'
SCRUTINY_REPORT = 'scrutiny_report'
PRESENTATION_SPEECH = 'presentation_speech'
HANSARD = 'hansard'
EXPLANATORY_STATEMENT = 'explanatory_statement'
COMPATIBILITY_STATEMENT = 'compatibility_statement'
```

### NT

```python
URL = 'url'
SHORT_TITLE = 'short_title'
EXPLANITORY_STATEMENT = 'explanatory_statement'
TEXT_URL = 'text_url'
STATUS = 'status'
SPONSOR = 'sponsor'
SERIAL_NO = 'serial_no'
PARLIAMENT_NO = 'parliament_no'
REMARKS = 'remarks'
INTRO_DATE = 'intro_date'
DATE = 'date'
```

### QLD

```python
ID = 'id'
URL = 'url'
PRINT_TYPE = 'print_type'
PARLIAMENT_NO = 'parliament_no'
DATE = 'date'
TITLE = 'title'
BILL_NUMBER = 'bill_number'
SERIES_ID = 'series_id' #  These 2 variables (series/desc)_id are used by the QLD bill API to deliver specific HTML fragments.
DESC_ID = 'desc_id'     #  Without these, we'd need some funky JavaScript interpretation, and you know I'm too lazy to write that. 
EXPLANATORY_NOTE = 'explanatory_note'
RENDITIONS = 'renditions'
SPONSOR = 'sponsor'
LONG_TITLE = 'long_title'
BILL_TYPE = 'bill_type'
```

### SA

```python
URL = 'url'
SHORT_TITLE = 'short_title'
SPONSOR = 'sponsor'
TEXTS = 'texts'
```

### TAS

```python
URL = 'url'
TITLE = 'title'
YEAR = 'year'
PASSED_LOWER = 'passed_lower'
PASSED_UPPER = 'passed_upper'
SPONSOR = 'sponsor'
BILL_TEXT_URL = 'bill_text_url'
WAS_AMENDED_UPPER = 'was_amended_upper'
WAS_AMENDED_LOWER = 'was_amended_lower'
ASSENTED = 'assented'
ACT_NO = 'act_no'
LOWER_FIRST_READING = 'lower_first_reading'
LOWER_SECOND_READING = 'lower_second_reading'
LOWER_THIRD_READING = 'lower_third_reading'
UPPER_FIRST_READING = 'upper_first_reading'
UPPER_SECOND_READING = 'upper_second_reading'
UPPER_THIRD_READING = 'upper_third_reading'
```

### VIC

```python
URL = 'url'
ID = 'id'
SHORT_TITLE = 'short_title'
STATUS = 'status'
STATUS_REPORT = 'status_report'
YEAR = 'year'
BILL_TYPE = 'bill_type'
EXPLANATORY_MEMORANDUM = 'explanatory_memorandum'
LOWER_SPONSOR = 'lower_sponsor'
CIRCULATION_PRINT = 'circulation_print'
UPPER_SPONSOR = 'upper_sponsor'
INTRODUCTION_PRINT = 'introduction_print'
PASSED_PRINT = 'passed_print'
AMENDED_PRINT = 'amended_print'
LOWER_FIRST_READING_PASSED = 'lower_first_reading_passed'
LOWER_SECOND_READING_PASSED = 'lower_second_reading_passed'
LOWER_SECOND_READING_MOVED = 'lower_second_reading_moved'
LOWER_THIRD_READING_PASSED = 'lower_third_reading_passed'
LOWER_THIRD_READING_MOVED = 'lower_third_reading_moved'
UPPER_FIRST_READING_PASSED = 'upper_first_reading_passed'
UPPER_SECOND_READING_PASSED = 'upper_second_reading_passed'
UPPER_SECOND_READING_MOVED = 'upper_second_reading_moved'
UPPER_THIRD_READING_PASSED = 'upper_third_reading_passed'
UPPER_THIRD_READING_MOVED = 'upper_third_reading_moved'
ASSENTED = 'assented'
ACT_NO = 'act_no'
```

### WA

```python
@dataclass
class Bill:
    name: str
    bill_no: str
    url: str
    bill_progress: Maybe[BillProgress]
    # from the detailed page
    synopsis: str
    private_members_bill: Maybe[str]
    status: str
    bill_history: List[Tuple[str, PdfUrl]]
    acts_amended: List[Tuple[str, PdfUrl]]
    related_committee_activity: List[Tuple[str, PdfUrl]]
    lc_supplementary: List[Tuple[str, PdfUrl]]
    messages: List[Tuple[str, PdfUrl]]
    progress_la: List[Tuple[str, datetime]]
    progress_lc: List[Tuple[str, datetime]]
    superseded_lc_supplementary: List[Tuple[str, PdfUrl]]
    comparisons_between_version: Tuple[List[Tuple[str, PdfUrl]], List[Tuple[str, PdfUrl]]]
    conference_of_managers: List[Tuple[str, PdfUrl]]
    notes: List[str]
```

**Comment by KipCrossing** [comment]
@king-millez 

I noticed that SA doesn't have much data. Are `TEXTS` just links to the pdf and word docs?

eg:

https://legislation.sa.gov.au/LZ/B/CURRENT/AGEING%20AND%20ADULT%20SAFEGUARDING%20(DISAPPLICATION%20OF%20TRANSITIONAL%20PROVISION)%20AMENDMENT%20BILL%202020_NAT%20COOK%20MP.aspx

**Comment by KipCrossing** [comment]
These are all basically the same thing - just might need come logic to squash them into common item.

```python
SPONSOR = "sponsor"
PORTFOLIO = "portfolio"
CARRIAGE_MEMBER = 'carriage_member'
PRESENTED_BY = 'presented_by'
LOWER_SPONSOR = 'lower_sponsor'
UPPER_SPONSOR = 'upper_sponsor'
```

(not sure what the WA one is)

These could all be replaced with `sponsor` or `author`.

**Comment by KipCrossing** [comment]
Also the links to the urls:

```python
TEXT_LINK = "text_link"
BILL_TEXT = 'text'
TEXT_URL = 'text_url'
TEXTS = 'texts'
BILL_TEXT_URL = 'bill_text_url'
```

It would be good if these all point to pdf's but idk

**Comment by KipCrossing** [comment]
Ok, I'm happy with the models, but i think we can still find common names across parliaments.

This is a BIG job though and may need a sandbox/mindmapesk  type tool to help solve it; and a sesh.

**Comment by king-millez** [comment]
> 
> 
> @king-millez
> 
> I noticed that SA doesn't have much data. Are `TEXTS` just links to the pdf and word docs?
> 
> eg:
> 
> https://legislation.sa.gov.au/LZ/B/CURRENT/AGEING%20AND%20ADULT%20SAFEGUARDING%20(DISAPPLICATION%20OF%20TRANSITIONAL%20PROVISION)%20AMENDMENT%20BILL%202020_NAT%20COOK%20MP.aspx

I believe so, I don't remember SA having very much data on their site...

**Pull request merged**
